site_name: شرح تثبيت هاكنتوش بالعربي
repo_url: https://github.com/arhackintosh/artutorial
site_description: اول و اكبر شرح عربي متفوح المصدر لتثبيت الهاكنتوش
site_author: ARhackintosh
copyright: https://github.com/ARhackintosh/ARtutorial/blob/intel/LICENSE
plugins:
  - autolinks
  - search # necessary for search to work
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago
theme:
  name: material
  language: ar
  font: false
  palette:
    scheme: slate
    primary: deep purple
    accent: indigo
