site_name: شرح تثبيت الهاكنتوش | هاكنتوش بالعربي
site_url: https://tutorial.xn--mgbg4a8cpdl.com
site_author: مجتمع هاكنتوش بالعربي
repo_name: ARhackintosh/ARtutorial
repo_url: https://github.com/arhackintosh/artutorial
copyright: حقوق هذا العمل محفوطه لهاكنتوش بالعربي تحت AGPLv3
site_description: شرح تثبيت الهاكنتوش من هاكنتوش بالعربي هو اول واكبر شرح عربي لتثبيت الهاكنتوش مع دعم اوبن كور وماك 11 بيج سر باللغه العربية.
docs_dir: 'source'

plugins:
  - autolinks
  - search # necessary for search to work
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago

theme:
  name: material
  custom_dir: overrides
  language: ar
  font: false
  logo: https://cdn.xn--mgbg4a8cpdl.com/logo.png
  favicon: https://cdn.xn--mgbg4a8cpdl.com/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: deep purple
    accent: indigo
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ARhackintosh
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/arhackintosh
    - icon: fontawesome/brands/telegram
      link: https://t.me/arhackintosh
    - icon: fontawesome/brands/discord
      link: https://discord.gg/s3qmDWm

extra_css:
  - extra/extra.css

nav:
    - الرئيسية: 'index.md'
    - البداية: 'start.md'
    - نسخ النظام:
      - 'macOS 11 Big Sur - بيج سر' : 'making-installer/Big-sur.md'
      - 'macOS 10.15 Catalina - كاتلينا او اقدم' : 'making-installer/Catalina-or-older.md'
    - تجهيز قسم ال EFI:
      - 'نقل ملفات اوبن كور': 'EFI-setup/Opencore.md'
      - اختيار التعريفات | Kext: 'EFI-setup/gathering-kexts.md'
      - 'ACPI': 'EFI-setup/ACPI.md'
      - 'الكونفق': 'EFI-setup/config.md'
    - تجهيز الكونفق:
      - 'Intel(PC)':
        - 'الجيل الثالث' : 'config-setup/3rd-gen.md'
        - 'الجيل الرابع و الخامس' : 'config-setup/4th-gen.md'
        - 'الجيل السادس' : 'config-setup/6th-gen.md'
        - 'الجيل السابع' : 'config-setup/7th-gen.md'
        - 'الجيل الثامن والتاسع' : 'config-setup/8th-gen.md' 
        - 'الجيل العاشر' : 'config-setup/10th-gen.md'
      - 'Ryzen(PC)': 'config-setup/AMD.md'
      - 'Intel(Laptop)':
        - 'الجيل الثالث' : 'config-setup/laptops/3rd-gen.md'
        - 'الجيل الرابع' : 'config-setup/laptops/4th-gen.md'
        - 'الجيل الخامس' : 'config-setup/laptops/5th-gen.md'
        - 'الجيل السادس' : 'config-setup/laptops/6th-gen.md'
        - 'الجيل السابع' : 'config-setup/laptops/7th-gen.md'
        - 'الجيل الثامن' : 'config-setup/laptops/8th-gen.md'
        - 'الجيل التاسع و comet lake' : 'config-setup/laptops/9th-gen.md'
        - 'ice lake' : 'config-setup/laptops/ice-lake.md'
    - 'تثبيت الماك':
      - 'الاقلاع': 'Installation/booting.md'
      - بعد التثبيت: 'Installation/post-install.md'
    - 'مجتمع هاكنتوش بالعربي': 'https://forum.هاكنتوش.com'
    - 'نسخة التطوير': '/dev'
    - 'تيليجرام': 'https://t.me/arhackintosh'
    - 'دسكورد': 'https://discord.gg/mNMtceb'



markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - meta
