site_name: شرح تثبيت هاكنتوش بالعربي
site_url: https://tutorial.xn--mgbg4a8cpdl.com
site_author: مجتمع هاكنتوش بالعربي
repo_name: ARhackintosh/ARtutorial
repo_url: https://github.com/arhackintosh/artutorial
copyright: مرخص تحت AGPLV3
site_description: اول و اكبر شرح عربي مفتوح المصدر لتثبيت الهاكنتوش

plugins:
  - autolinks
  - search # necessary for search to work
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date

theme:
  name: material
  language: ar
  font: false
  favicon: ./img/favicon.ico
  logo: ./img/logo.png
  repo: fontawesome/brands/github
  features:
    - tabs
  palette:
    scheme: slate
    primary: deep purple
    accent: indigo
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ARhackintosh
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/arhackintosh


markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
