site_name: شرح تثبيت الهاكنتوش من مجتمع هاكنتوش بالعربي
site_url: https://tutorial.xn--mgbg4a8cpdl.com
site_author: مجتمع هاكنتوش بالعربي
repo_name: ARhackintosh/ARtutorial
repo_url: https://github.com/arhackintosh/artutorial
copyright: مرخص تحت AGPLV3
site_description: اول و اكبر شرح عربي مفتوح المصدر لتثبيت الهاكنتوش

plugins:
  - autolinks
  - search # necessary for search to work
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago

theme:
  name: material
  language: ar
  font: false
  logo: img/logo.png
  favicon: img/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - instant
  palette:
    scheme: slate
    primary: deep purple
    accent: indigo
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ARhackintosh
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/arhackintosh

nav:
    - شرح تثبيت الهاكنتوش من هاكنتوش بالعربي: 'docs/index.md'
    - 'docs/start.md'
    - 'docs/gathering-kexts.md'
    - اختيار الكونفق:
      - كمبيوتر مكتبي: 'docs/config-setup/desktops.md'
      - لابتوب: 'docs/config-setup/laptops.md'
    - 'تثبيت بدون انترنت':
      - 'تنزيل النظام': 'docs/offline-installer/downloading-the-full-macos-installer.md'
      - 'نسخ النظام': 'docs/offline-installer/offline-usb-setup.md'
    - 'تثبيت مع انترنت':
      - 'تنزيل النظام': 'docs/online-installer/downloading-online-recovery.md'
      - 'نسخ النظام': 'docs/offline-installer/online-usb-setup.md'
    - بعد نسخ الماك : 'docs/after-copying-the-installer'


markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
