site_name: شرح تثبيت الهاكنتوش من مجتمع هاكنتوش بالعربي
site_url: https://tutorial.xn--mgbg4a8cpdl.com
site_author: مجتمع هاكنتوش بالعربي
repo_name: ARhackintosh/ARtutorial
repo_url: https://github.com/arhackintosh/artutorial
copyright: مرخص تحت AGPLV3
site_description: اول و اكبر شرح عربي مفتوح المصدر لتثبيت الهاكنتوش

plugins:
  - autolinks
  - search # necessary for search to work
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago

theme:
  name: material
  language: ar
  font: false
  logo: img/logo.png
  favicon: img/logo.png
  icon:
    repo: fontawesome/brands/github
#  features:
#    - instant
  palette:
    scheme: slate
    primary: deep purple
    accent: indigo
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ARhackintosh
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/arhackintosh

nav:
    - شرح تثبيت الهاكنتوش من هاكنتوش بالعربي: 'index.md'
    - البداية: 'start'
    - اختيار التعريفات(kex): 'gathering-kexts'
    - اختيار الكونفق:
      - 'كمبيوتر مكتبي': 'config-setup/desktops'
      - 'لابتوب': 'config-setup/laptops'
    - 'تثبيت بدون انترنت':
      - 'تنزيل النظام': 'offline-installer/downloading-the-full-macos-installer'
      - 'نسخ النظام': 'offline-installer/offline-usb-setup'
    - تثبيت مع انترنت:
      - تنزيل النظام: './online-installer/downloading-online-recovery'
      - نسخ النظام: './offline-installer/online-usb-setup'
    - 'بعد نسخ الماك':
      - 'الاقلاع': 'booting.md'



markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
