site_name: شرح تثبيت هاكنتوش بالعربي
site_url: tutorial.xn--mgbg4a8cpdl.com
repo_url: https://github.com/arhackintosh/artutorial
site_description: اول و اكبر شرح عربي مفتوح المصدر لتثبيت الهاكنتوش
site_author: ARhackintosh
copyright: https://github.com/ARhackintosh/ARtutorial/blob/intel/LICENSE
plugins:
  - autolinks
  - search # necessary for search to work
theme:
  name: material
  language: ar
  font: false
  palette:
    scheme: slate
    primary: deep purple
    accent: indigo
