site_name: شرح تثبيت هاكنتوش بالعربي
site_url: https://tutorial.xn--mgbg4a8cpdl.com
repo_url: https://github.com/arhackintosh/artutorial
site_description: اول و اكبر شرح عربي مفتوح المصدر لتثبيت الهاكنتوش
site_author: ARhackintosh
copyright: مرخص تحت AGPLV3

theme:
  name: material
  language: ar
  font: false
  palette:
    scheme: slate
    primary: deep purple
    accent: indigo
