site_name: شرح تثبيت الهاكنتوش من مجتمع هاكنتوش بالعربي
site_url: https://tutorial.xn--mgbg4a8cpdl.com
site_author: مجتمع هاكنتوش بالعربي
repo_name: ARhackintosh/ARtutorial
repo_url: https://github.com/arhackintosh/artutorial
copyright: مرخص تحت AGPLV3
site_description: اول و اكبر شرح عربي مفتوح المصدر لتثبيت الهاكنتوش

plugins:
  - autolinks
  - search # necessary for search to work
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago

theme:
  name: material
  language: ar
  font:
    text: Tajawal
  logo: img/logo.png
  favicon: img/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
  palette:
    scheme: slate
    primary: deep purple
    accent: indigo
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ARhackintosh
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/arhackintosh

extra_css:
  - extra.css

nav:
    - شرح تثبيت الهاكنتوش من هاكنتوش بالعربي: 'index.md'
    - البداية: 'start.md'
    - نسخ النظام:
      - 'بيج سر' : 'making-installer/Big-sur.md'
      - 'كاتلينا او اقدم' : 'making-installer/Catalina-or-older.md'
    - تجهيز قسم ال EFI:
      - 'نقل ملفات اوبن كور': 'EFI-setup/Opencore.md'
      - اختيار التعريفات | Kext: 'EFI-setup/gathering-kexts.md'
      - 'ACPI': 'EFI-setup/ACPI.md'
      - 'الكونفق': 'EFI-setup/config.md'
    - تجهيز الكونفق:
      - 'Intel(PC)':
        - 'الجيل الثالث' : 'config-setup/3rd-gen.md'
        - 'الجيل الرابع و الخامس' : 'config-setup/4th-gen.md'
        - 'الجيل السادس' : 'config-setup/6th-gen.md'
        - 'الجيل السابع' : 'config-setup/7th-gen.md'
        - 'الجيل الثامن' : 'config-setup/8th-gen.md' 
        - 'الجيل التاسع' : 'config-setup/9th-gen.md' 
        - 'الجيل العاشر' : 'config-setup/10th-gen.md'
      - 'Ryzen(PC)': 'config-setup/AMD.md'
      - 'Intel(Laptop)':
        - 'الجيل الثالث' : 'config-setup/laptops/3rd-gen.md'
        - 'الجيل الرابع' : 'config-setup/laptops/4th-gen.md'
        - 'الجيل الخامس' : 'config-setup/laptops/5th-gen.md'
        - 'الجيل السادس' : 'config-setup/laptops/6th-gen.md'
        - 'الجيل السابع' : 'config-setup/laptops/7th-gen.md'
        - 'الجيل الثامن' : 'config-setup/laptops/8th-gen.md'
        - 'الجيل التاسع' : 'config-setup/laptops/9th-gen.md'
        - 'Comet lake' : 'config-setup/laptops/comet-lake.md'
        - 'ice lake' : 'config-setup/laptops/ice-lake.md'
    - 'بعد نسخ الماك':
      - 'الاقلاع': 'after-copying-the-installer/booting.md'
      - بعد التثبيت: 'after-copying-the-installer/post-install.md'



markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
