site_name: شرح تثبيت الهاكنتوش | هاكنتوش بالعربي
site_url: https://tutorial.xn--mgbg4a8cpdl.com
site_author: مجتمع هاكنتوش بالعربي
repo_name: ARhackintosh/ARtutorial
repo_url: https://github.com/ARhackintosh/ARtutorial
copyright: حقوق هذا العمل محفوطه لهاكنتوش بالعربي تحت AGPLv3
site_description: شرح تثبيت الهاكنتوش من هاكنتوش بالعربي هو اول واكبر شرح عربي لتثبيت الهاكنتوش مع دعم OpenCore وmacOS 11 Big Sur باللغة العربية.
docs_dir: 'source'

plugins:
  - autolinks
  - search # necessary for search to work
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago
  - macros
  - social:
      cards_font: Tajawal
  - glightbox:
      effect: fade
      skip_classes:
        - skip-lightbox

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - toc.integrate
    - navigation.top
  language: ar
  font: false
  logo: img/artutorial-logo.webp
  favicon: img/artutorial-logo.webp
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ARhackintosh
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/arhackintosh
    - icon: fontawesome/brands/telegram
      link: https://t.me/arhackintosh
    - icon: matrix
      link: https://matrix.to/#/#arhackintosh:utwente.io
  oc:
    version: 0.7.2
    git: https://github.com/acidanthera/OpenCorePkg/releases/tag/0.7.2


extra_css:
  - extra/extra.css

nav:
    - الرئيسية: 'index.md'
    - البداية: 'start.md'
    - تجهيز ملف ال EFI:
      - 'نقل ملفات اوبن كور': 'EFI-setup/Opencore.md'
      - 'اختيار التعريفات | Kext': 'EFI-setup/gathering-kexts.md'
      - 'ACPI': 'EFI-setup/ACPI.md'
      - 'الكونفق': 'EFI-setup/config.md'
    - تجهيز الكونفق:
      - Intel(PC):
        - 'الجيل الثالث' : 'config-setup/3rd-gen.md'
        - 'الجيل الرابع و الخامس' : 'config-setup/4th-gen.md'
        - 'الجيل السادس' : 'config-setup/6th-gen.md'
        - 'الجيل السابع' : 'config-setup/7th-gen.md'
        - 'الجيل الثامن والتاسع' : 'config-setup/8th-gen.md' 
        - 'الجيل العاشر' : 'config-setup/10th-gen.md'
      - 'Ryzen(PC)': 'config-setup/AMD.md'
      - Intel(Laptop):
        - 'الجيل الثالث' : 'config-setup/laptops/3rd-gen.md'
        - 'الجيل الرابع' : 'config-setup/laptops/4th-gen.md'
        - 'الجيل الخامس' : 'config-setup/laptops/5th-gen.md'
        - 'الجيل السادس' : 'config-setup/laptops/6th-gen.md'
        - 'الجيل السابع' : 'config-setup/laptops/7th-gen.md'
        - 'الجيل الثامن' : 'config-setup/laptops/8th-gen.md'
        - 'الجيل التاسع و comet lake' : 'config-setup/laptops/9th-gen.md'
        - 'ice lake' : 'config-setup/laptops/ice-lake.md'
    - تنزيل ونسخ الماك وال EFI:
      - 'macOS 11 Big Sur - بيج سر' : 'making-installer/Big-sur.md'
      - 'macOS 10.15 Catalina - كاتلينا او اقدم' : 'making-installer/Catalina-or-older.md'
    - تثبيت الماك:
      - 'الاقلاع': 'Installation/booting.md'
      - 'بعد التثبيت': 'Installation/post-install.md'
    - 'مجتمع هاكنتوش بالعربي': 'https://forum.هاكنتوش.com'
    - 'تيليجرام': 'https://t.me/arhackintosh'
    - 'ماتركس': 'https://matrix.to/#/#arhackintosh:utwente.io'



markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
