site_name: شرح تثبيت الهاكنتوش من مجتمع هاكنتوش بالعربي
site_url: https://tutorial.xn--mgbg4a8cpdl.com
site_author: مجتمع هاكنتوش بالعربي
repo_name: ARhackintosh/ARtutorial
repo_url: https://github.com/arhackintosh/artutorial
copyright: مرخص تحت AGPLV3
site_description: اول و اكبر شرح عربي مفتوح المصدر لتثبيت الهاكنتوش

plugins:
  - autolinks
  - search # necessary for search to work
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago

theme:
  name: material
  language: ar
  font:
    text: Tajawal
  logo: img/logo.png
  favicon: img/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - instant
  palette:
    scheme: slate
    primary: deep purple
    accent: indigo
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ARhackintosh
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/arhackintosh

extra_css:
  - extra.css

nav:
    - شرح تثبيت الهاكنتوش من هاكنتوش بالعربي: 'index.md'
    - البداية: 'start.md'
    - اختيار التعريفات(kext): 'gathering-kexts.md'
    - اختيار الكونفق:
      - 'Intel(Pc):
        - 'جيل الثالث' : 'config-setup/3rd-gen.md'
      - 'Ryzen(PC)': 'config-setup/AMD.md'
      - 'Intel(Laptop)':
        - 'جيل الثالث' : 'config-setup/laptops/3rd-gen.md'
    - 'تثبيت بدون انترنت':
      - 'تنزيل النظام': 'offline-installer/downloading-the-full-macos-installer.md'
      - 'نسخ النظام': 'offline-installer/offline-usb-setup.md'
    - تثبيت مع انترنت:
      - تنزيل النظام: 'online-installer/downloading-online-recovery.md'
      - نسخ النظام: 'online-installer/online-usb-setup.md'
    - 'بعد نسخ الماك':
      - 'الاقلاع': 'after-copying-the-installer/booting.md'
      - بعد التثبيت: 'after-copying-the-installer/post-install.md'



markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
