name: dev-PR-test

on:
  workflow_dispatch:
  pull_request:
    branches: [ V3-Dev ]
  pull_request_review:
    types: [edited, dismissed]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3 
      with:
        persist-credentials: false
        fetch-depth: '0'

    # setup python
    - name: Set up Python 3.10
      uses: actions/setup-python@v3.1.2
      with:
        python-version: 3.10.2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install -U pip wheel
        python -m pip install -r requirements.txt
        git submodule update --init --recursive
        pip show mkdocs-material

    - name: mkdocs build
      run: mkdocs build --clean --verbose -d site

    - name: Cache pip files
      uses: actions/cache@v3.0.2
      env:
        cache-name: pip-reg
      with:
        path: $HOME/.cache/pip
        key: pip-reg
