name: Release-Build

on:
  # release:
  #   branches: [ v2-dev ]
  workflow_dispatch:
    inputs:
      version:
        description: 'رقم الاصدار'
        required: true
        default: 'الاخير'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2 
      with:
        persist-credentials: false
        fetch-depth: '0'

    # setup python
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install -U pip wheel
        python -m pip install -r requirements.txt
        pip show mkdocs-material

    - name: mkdocs build
      run: mkdocs build --clean --verbose -d site

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: site # The folder the action should deploy.
        commit-message: "Release-Build: ${{ github.event.inputs.version }} رفع الاصدار"
        clean: true # Automatically remove deleted files from the deploy branch
        clean-exclude: dev #عدم حذف صفحه نسخه التطوير

    - name: Cache pip files
      uses: actions/cache@v2.1.6
      env:
        cache-name: pip-reg
      with:
        path: $HOME/.cache/pip
        key: pip-reg